#!/usr/bin/python
import json
import os
import sys
import pwd
import grp
import shutil
from os.path import abspath, exists
from SystemConfiguration import SCDynamicStoreCopyConsoleUser

username = (SCDynamicStoreCopyConsoleUser(None, None, None) or [None])[0]
username = [username,""][username in [u"loginwindow", None, u""]]

f_path = abspath("config.txt")

if exists(f_path):
    with open(f_path) as f:
        config=contents = [x.strip() for x in f.readlines()]


path ="/users/%s/Library/Application Support/CollibraForDesktop/" % (username)
json_file = "%s/config.json" % (path)

#Deal with the json if it doesn't esist
if not os.path.exists(path):
    print "creating directory"
    os.makedirs(path)
    uid, gid =  pwd.getpwnam(username).pw_uid, grp.getgrnam('staff').gr_gid

    print "Copying settings"
    shutil.copyfile(abspath("config.json"), json_file)


    #properly set permissions
    os.chown(path, uid, gid)
    for dirpath, dirnames, filenames in os.walk(path):
        for dname in dirnames:
            os.chown(os.path.join(dirpath, dname), uid, gid)
            for fname in filenames:
                os.chown(os.path.join(dirpath, fname), uid, gid)

    #Edit the templated settings file
    with open(json_file, 'r') as f:
        data = json.load(f)
        data['instance']= "%s" % (config[1])
        data['shortcut'] = "%s" % (config[2])
        data['configurable'] = "%s" % (config[3])
        data['disableShortcut'] = "%s" % (config[4])
        data['shortcut'] = "%s" % (config[5])
        data['disableAutoUpdates'] = "%s" % (config[6])
        data['dgcName'] = "%s" % (config[7])
        data['defaultFilterId'] = "%s" % (config[8])
        os.remove(json_file)
        with open(json_file, 'w') as f:
            json.dump(data, f, indent=4)
            f.close()

#edit pre-existing setting for new url.
if os.path.exists(path):
    with open(json_file, 'r') as f:
        data = json.load(f)
        data['instance']= "%s" % (config[1])
        data['disableAutoUpdates'] = "%s" % (config[6])
        data['dgcName'] = "%s" % (config[7])
        os.remove(json_file)
        with open(json_file, 'w') as f:
            json.dump(data, f, indent=4)
            f.close()
